power: supply: qcom: SMB1360: Fix compilation issue
Regulator API was changed on k4.4

drivers/power/supply/qcom/smb1360-charger-fg.c: In function 'smb1360_regulator_init':
drivers/power/supply/qcom/smb1360-charger-fg.c:3799:14: error: incompatible type for argument 3 of 'of_get_regulator_init_data'
  init_data = of_get_regulator_init_data(chip->dev, chip->dev->of_node, cfg);

Signed-off-by: Pavel Dubrova <pashadubrova@gmail.com>